# Generated by Django 5.0 on 2024-01-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_tbl_location'),
        ('Guest', '0006_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='MemberDocs/')),
                ('video', models.FileField(upload_to='MemberDocs')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_worktype')),
            ],
        ),
    ]
