# Generated by Django 5.0 on 2024-01-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='MemberDocs/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_work')),
            ],
        ),
    ]
