# Generated by Django 5.0 on 2024-01-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_tbl_wgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='MemberDocs/')),
                ('rate', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_work')),
            ],
        ),
    ]
