# Generated by Django 5.0 on 2024-01-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_seller',
        ),
    ]
