# Generated by Django 5.0 on 2024-01-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_wcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_wbooking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tbl_wcart',
            old_name='wbooking_id',
            new_name='wbooking',
        ),
        migrations.RenameField(
            model_name='tbl_wcart',
            old_name='works_id',
            new_name='works',
        ),
    ]
