# Generated by Django 5.0 on 2024-02-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_seller'),
        ('User', '0005_tbl_mcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('from_seller', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_seller', to='Guest.tbl_seller')),
                ('from_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='Guest.tbl_user')),
                ('to_seller', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_seller', to='Guest.tbl_seller')),
                ('to_user', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='Guest.tbl_user')),
            ],
        ),
    ]
