# Generated by Django 5.0 on 2024-03-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_tbl_material'),
        ('User', '0006_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('user_review', models.CharField(max_length=50)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_work')),
            ],
        ),
    ]
