# Generated by Django 5.0 on 2024-03-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.tbl_mcart')),
                ('wcart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.tbl_wcart')),
            ],
        ),
    ]
